
USE `arigasol`;

delete from appmenus;

/*Data for the table `appmenus` */

insert into `appmenus` (`aplicacion`,`Name`,`caption`,`indice`,`padre`,`orden`,`Contador`) values ('Arigasol','mnE_Util','Solicitud Tarjetas',2,73,2,75);
insert into `appmenus` (`aplicacion`,`Name`,`caption`,`indice`,`padre`,`orden`,`Contador`) values ('Arigasol','mnE_Tanques','Datos Tanques/Mangueras',1,68,1,69);
insert into `appmenus` (`aplicacion`,`Name`,`caption`,`indice`,`padre`,`orden`,`Contador`) values ('Arigasol','mnE_Estadist','Certificado de Gasoleo B',11,56,11,67);
insert into `appmenus` (`aplicacion`,`Name`,`caption`,`indice`,`padre`,`orden`,`Contador`) values ('Arigasol','mnE_Estadist','Evolución Mensual Clientes',10,56,10,66);
insert into `appmenus` (`aplicacion`,`Name`,`caption`,`indice`,`padre`,`orden`,`Contador`) values ('Arigasol','mnE_Estadist','Declaraciones Gasóleo Profesional',9,56,9,65);
insert into `appmenus` (`aplicacion`,`Name`,`caption`,`indice`,`padre`,`orden`,`Contador`) values ('Arigasol','mnE_Estadist','Ventas Artículos por Tarjeta',7,56,7,63);
insert into `appmenus` (`aplicacion`,`Name`,`caption`,`indice`,`padre`,`orden`,`Contador`) values ('Arigasol','mnE_Estadist','Ventas por Cliente',3,56,3,59);
insert into `appmenus` (`aplicacion`,`Name`,`caption`,`indice`,`padre`,`orden`,`Contador`) values ('Arigasol','mnE_Estadist','Histórico Facturas',1,56,1,57);
insert into `appmenus` (`aplicacion`,`Name`,`caption`,`indice`,`padre`,`orden`,`Contador`) values ('Arigasol','mnF_FacturacionAjena','-',9,45,9,54);
insert into `appmenus` (`aplicacion`,`Name`,`caption`,`indice`,`padre`,`orden`,`Contador`) values ('Arigasol','mnF_FacturacionAjena','-',7,45,7,52);
insert into `appmenus` (`aplicacion`,`Name`,`caption`,`indice`,`padre`,`orden`,`Contador`) values ('Arigasol','mnF_FacturacionAjena','-',5,45,5,50);
insert into `appmenus` (`aplicacion`,`Name`,`caption`,`indice`,`padre`,`orden`,`Contador`) values ('Arigasol','mnF_FacturacionAjena','Histórico Facturas',4,45,4,49);
insert into `appmenus` (`aplicacion`,`Name`,`caption`,`indice`,`padre`,`orden`,`Contador`) values ('Arigasol','mnF_Facturacion','Grabación modelo Gasoleo B',11,33,11,44);
insert into `appmenus` (`aplicacion`,`Name`,`caption`,`indice`,`padre`,`orden`,`Contador`) values ('Arigasol','mnF_Facturacion','Facturas Rectificativas',10,33,10,43);
insert into `appmenus` (`aplicacion`,`Name`,`caption`,`indice`,`padre`,`orden`,`Contador`) values ('Arigasol','mnF_Facturacion','Contabilizar Facturación',5,33,5,38);
insert into `appmenus` (`aplicacion`,`Name`,`caption`,`indice`,`padre`,`orden`,`Contador`) values ('Arigasol','mnG_Ventas','Cuadre diario',10,20,10,30);
insert into `appmenus` (`aplicacion`,`Name`,`caption`,`indice`,`padre`,`orden`,`Contador`) values ('Arigasol','mnG_Ventas','Cambio de Cliente',8,20,8,28);
insert into `appmenus` (`aplicacion`,`Name`,`caption`,`indice`,`padre`,`orden`,`Contador`) values ('Arigasol','mnG_Ventas','Informe Prefacturación',5,20,5,25);
insert into `appmenus` (`aplicacion`,`Name`,`caption`,`indice`,`padre`,`orden`,`Contador`) values ('Arigasol','mnG_Ventas','Traspaso datos Postes',1,20,1,21);
insert into `appmenus` (`aplicacion`,`Name`,`caption`,`indice`,`padre`,`orden`,`Contador`) values ('Arigasol','mnP_Generales','-',17,1,17,18);
insert into `appmenus` (`aplicacion`,`Name`,`caption`,`indice`,`padre`,`orden`,`Contador`) values ('Arigasol','mnP_Generales','Formas de pago',14,1,14,15);
insert into `appmenus` (`aplicacion`,`Name`,`caption`,`indice`,`padre`,`orden`,`Contador`) values ('Arigasol','mnP_Generales','Familias',11,1,11,12);
insert into `appmenus` (`aplicacion`,`Name`,`caption`,`indice`,`padre`,`orden`,`Contador`) values ('Arigasol','mnP_Generales','Empleados',10,1,10,11);
insert into `appmenus` (`aplicacion`,`Name`,`caption`,`indice`,`padre`,`orden`,`Contador`) values ('Arigasol','mnP_Generales','Tipo de Crédito ',5,1,5,6);
insert into `appmenus` (`aplicacion`,`Name`,`caption`,`indice`,`padre`,`orden`,`Contador`) values ('Arigasol','mnP_Generales','Parámetros',2,1,2,3);
insert into `appmenus` (`aplicacion`,`Name`,`caption`,`indice`,`padre`,`orden`,`Contador`) values ('Arigasol','mnP_Generales','Datos de Empresa',1,1,1,2);
insert into `appmenus` (`aplicacion`,`Name`,`caption`,`indice`,`padre`,`orden`,`Contador`) values ('Arigasol','mnE_Util','Rangos Horarios',1,73,1,74);
insert into `appmenus` (`aplicacion`,`Name`,`caption`,`indice`,`padre`,`orden`,`Contador`) values ('Arigasol','mnUtil','Utilidades',NULL,0,7,73);
insert into `appmenus` (`aplicacion`,`Name`,`caption`,`indice`,`padre`,`orden`,`Contador`) values ('Arigasol','mnE_Tanques','Estadística de Artículos',4,68,4,72);
insert into `appmenus` (`aplicacion`,`Name`,`caption`,`indice`,`padre`,`orden`,`Contador`) values ('Arigasol','mnE_Tanques','Impresión Cierre de Turno',3,68,3,71);
insert into `appmenus` (`aplicacion`,`Name`,`caption`,`indice`,`padre`,`orden`,`Contador`) values ('Arigasol','mnE_Tanques','Datos Recaudación',2,68,2,70);
insert into `appmenus` (`aplicacion`,`Name`,`caption`,`indice`,`padre`,`orden`,`Contador`) values ('Arigasol','mnTanques','Tanques-Mangueras',NULL,0,6,68);
insert into `appmenus` (`aplicacion`,`Name`,`caption`,`indice`,`padre`,`orden`,`Contador`) values ('Arigasol','mnE_Estadist','Resumen por Rangos Horarios',8,56,8,64);
insert into `appmenus` (`aplicacion`,`Name`,`caption`,`indice`,`padre`,`orden`,`Contador`) values ('Arigasol','mnE_Estadist','Resumen Ventas Diarias',6,56,6,62);
insert into `appmenus` (`aplicacion`,`Name`,`caption`,`indice`,`padre`,`orden`,`Contador`) values ('Arigasol','mnE_Estadist','Resumen Ventas Artículos',5,56,5,61);
insert into `appmenus` (`aplicacion`,`Name`,`caption`,`indice`,`padre`,`orden`,`Contador`) values ('Arigasol','mnE_Estadist','Ventas Artículos por Cliente',4,56,4,60);
insert into `appmenus` (`aplicacion`,`Name`,`caption`,`indice`,`padre`,`orden`,`Contador`) values ('Arigasol','mnE_Estadist','Diario de Facturación',2,56,2,58);
insert into `appmenus` (`aplicacion`,`Name`,`caption`,`indice`,`padre`,`orden`,`Contador`) values ('Arigasol','mnEstadisticas','Estadísticas',NULL,0,5,56);
insert into `appmenus` (`aplicacion`,`Name`,`caption`,`indice`,`padre`,`orden`,`Contador`) values ('Arigasol','mnF_FacturacionAjena','Traspaso Datos Cooperativas',10,45,10,55);
insert into `appmenus` (`aplicacion`,`Name`,`caption`,`indice`,`padre`,`orden`,`Contador`) values ('Arigasol','mnF_FacturacionAjena','Facturas de Abonos a Socios',8,45,8,53);
insert into `appmenus` (`aplicacion`,`Name`,`caption`,`indice`,`padre`,`orden`,`Contador`) values ('Arigasol','mnF_FacturacionAjena','Contabilización en Tesorería',6,45,6,51);
insert into `appmenus` (`aplicacion`,`Name`,`caption`,`indice`,`padre`,`orden`,`Contador`) values ('Arigasol','mnF_FacturacionAjena','-',3,45,3,48);
insert into `appmenus` (`aplicacion`,`Name`,`caption`,`indice`,`padre`,`orden`,`Contador`) values ('Arigasol','mnF_FacturacionAjena','Reimpresión de Facturas',2,45,2,47);
insert into `appmenus` (`aplicacion`,`Name`,`caption`,`indice`,`padre`,`orden`,`Contador`) values ('Arigasol','mnF_FacturacionAjena','Facturación',1,45,1,46);
insert into `appmenus` (`aplicacion`,`Name`,`caption`,`indice`,`padre`,`orden`,`Contador`) values ('Arigasol','mnFacturacionAjena','Facturación Ajena',1,0,4,45);
insert into `appmenus` (`aplicacion`,`Name`,`caption`,`indice`,`padre`,`orden`,`Contador`) values ('Arigasol','mnF_Facturacion','Facturas de Abonos a Clientes',9,33,9,42);
insert into `appmenus` (`aplicacion`,`Name`,`caption`,`indice`,`padre`,`orden`,`Contador`) values ('Arigasol','mnF_Facturacion','-',8,33,8,41);
insert into `appmenus` (`aplicacion`,`Name`,`caption`,`indice`,`padre`,`orden`,`Contador`) values ('Arigasol','mnF_Facturacion','Localizador Tickets',7,33,7,40);
insert into `appmenus` (`aplicacion`,`Name`,`caption`,`indice`,`padre`,`orden`,`Contador`) values ('Arigasol','mnF_Facturacion','-',6,33,6,39);
insert into `appmenus` (`aplicacion`,`Name`,`caption`,`indice`,`padre`,`orden`,`Contador`) values ('Arigasol','mnF_Facturacion','-',4,33,4,37);
insert into `appmenus` (`aplicacion`,`Name`,`caption`,`indice`,`padre`,`orden`,`Contador`) values ('Arigasol','mnF_Facturacion','Reimpresión de Facturas',3,33,3,36);
insert into `appmenus` (`aplicacion`,`Name`,`caption`,`indice`,`padre`,`orden`,`Contador`) values ('Arigasol','mnF_Facturacion','Facturación',2,33,2,35);
insert into `appmenus` (`aplicacion`,`Name`,`caption`,`indice`,`padre`,`orden`,`Contador`) values ('Arigasol','mnF_Facturacion','Traspaso Facturas Tpv',1,33,1,34);
insert into `appmenus` (`aplicacion`,`Name`,`caption`,`indice`,`padre`,`orden`,`Contador`) values ('Arigasol','mnFacturacion','Facturación',NULL,0,3,33);
insert into `appmenus` (`aplicacion`,`Name`,`caption`,`indice`,`padre`,`orden`,`Contador`) values ('Arigasol','mnG_Ventas','Contabilizar Cierre Turno',12,20,12,32);
insert into `appmenus` (`aplicacion`,`Name`,`caption`,`indice`,`padre`,`orden`,`Contador`) values ('Arigasol','mnG_Ventas','-',11,20,11,31);
insert into `appmenus` (`aplicacion`,`Name`,`caption`,`indice`,`padre`,`orden`,`Contador`) values ('Arigasol','mnG_Ventas','-',9,20,9,29);
insert into `appmenus` (`aplicacion`,`Name`,`caption`,`indice`,`padre`,`orden`,`Contador`) values ('Arigasol','mnG_Ventas','Comprobación descuadres',7,20,7,27);
insert into `appmenus` (`aplicacion`,`Name`,`caption`,`indice`,`padre`,`orden`,`Contador`) values ('Arigasol','mnG_Ventas','Buscar errores Albaranes',6,20,6,26);
insert into `appmenus` (`aplicacion`,`Name`,`caption`,`indice`,`padre`,`orden`,`Contador`) values ('Arigasol','mnG_Ventas','Resumen Ventas Articulos',4,20,4,24);
insert into `appmenus` (`aplicacion`,`Name`,`caption`,`indice`,`padre`,`orden`,`Contador`) values ('Arigasol','mnG_Ventas','Albaranes',3,20,3,23);
insert into `appmenus` (`aplicacion`,`Name`,`caption`,`indice`,`padre`,`orden`,`Contador`) values ('Arigasol','mnG_Ventas','-',2,20,2,22);
insert into `appmenus` (`aplicacion`,`Name`,`caption`,`indice`,`padre`,`orden`,`Contador`) values ('Arigasol','mnGeneral','Ventas Diarias',NULL,0,2,20);
insert into `appmenus` (`aplicacion`,`Name`,`caption`,`indice`,`padre`,`orden`,`Contador`) values ('Arigasol','mnP_Generales','Salir',18,1,18,19);
insert into `appmenus` (`aplicacion`,`Name`,`caption`,`indice`,`padre`,`orden`,`Contador`) values ('Arigasol','mnP_Generales','Grupo de Empresas',16,1,16,17);
insert into `appmenus` (`aplicacion`,`Name`,`caption`,`indice`,`padre`,`orden`,`Contador`) values ('Arigasol','mnP_Generales','Bancos propios',15,1,15,16);
insert into `appmenus` (`aplicacion`,`Name`,`caption`,`indice`,`padre`,`orden`,`Contador`) values ('Arigasol','mnP_Generales','Situaciones',13,1,13,14);
insert into `appmenus` (`aplicacion`,`Name`,`caption`,`indice`,`padre`,`orden`,`Contador`) values ('Arigasol','mnP_Generales','Artículos',12,1,12,13);
insert into `appmenus` (`aplicacion`,`Name`,`caption`,`indice`,`padre`,`orden`,`Contador`) values ('Arigasol','mnP_Generales','Clientes',9,1,9,10);
insert into `appmenus` (`aplicacion`,`Name`,`caption`,`indice`,`padre`,`orden`,`Contador`) values ('Arigasol','mnP_Generales','Colectivos',8,1,8,9);
insert into `appmenus` (`aplicacion`,`Name`,`caption`,`indice`,`padre`,`orden`,`Contador`) values ('Arigasol','mnP_Generales','-',7,1,7,8);
insert into `appmenus` (`aplicacion`,`Name`,`caption`,`indice`,`padre`,`orden`,`Contador`) values ('Arigasol','mnP_Generales','Usuarios',6,1,6,7);
insert into `appmenus` (`aplicacion`,`Name`,`caption`,`indice`,`padre`,`orden`,`Contador`) values ('Arigasol','mnP_Generales','Tipos de Documentos',4,1,4,5);
insert into `appmenus` (`aplicacion`,`Name`,`caption`,`indice`,`padre`,`orden`,`Contador`) values ('Arigasol','mnP_Generales','Tipos de Movimiento',3,1,3,4);
insert into `appmenus` (`aplicacion`,`Name`,`caption`,`indice`,`padre`,`orden`,`Contador`) values ('Arigasol','mnParametros','Datos Básicos',1,0,1,1);
insert into `appmenus` (`aplicacion`,`Name`,`caption`,`indice`,`padre`,`orden`,`Contador`) values ('Arigasol','mnE_Soporte2','Acerca de',NULL,86,3,89);
insert into `appmenus` (`aplicacion`,`Name`,`caption`,`indice`,`padre`,`orden`,`Contador`) values ('Arigasol','mnp_Barra2','-',NULL,86,2,88);
insert into `appmenus` (`aplicacion`,`Name`,`caption`,`indice`,`padre`,`orden`,`Contador`) values ('Arigasol','mnE_Soporte1','Web Soporte',NULL,86,1,87);
insert into `appmenus` (`aplicacion`,`Name`,`caption`,`indice`,`padre`,`orden`,`Contador`) values ('Arigasol','mnSoporte','Soporte',NULL,0,8,86);
insert into `appmenus` (`aplicacion`,`Name`,`caption`,`indice`,`padre`,`orden`,`Contador`) values ('Arigasol','mnE_Util','Copia de Seguridad local',12,73,12,85);
insert into `appmenus` (`aplicacion`,`Name`,`caption`,`indice`,`padre`,`orden`,`Contador`) values ('Arigasol','mnE_Util','Deshacer Facturación',11,73,11,84);
insert into `appmenus` (`aplicacion`,`Name`,`caption`,`indice`,`padre`,`orden`,`Contador`) values ('Arigasol','mnE_Util','-',10,73,10,83);
insert into `appmenus` (`aplicacion`,`Name`,`caption`,`indice`,`padre`,`orden`,`Contador`) values ('Arigasol','mnE_Util','Revisión de caracteres en Multibase',9,73,9,82);
insert into `appmenus` (`aplicacion`,`Name`,`caption`,`indice`,`padre`,`orden`,`Contador`) values ('Arigasol','mnE_Util','-',8,73,8,81);
insert into `appmenus` (`aplicacion`,`Name`,`caption`,`indice`,`padre`,`orden`,`Contador`) values ('Arigasol','mnE_Util','Comprobación Impuesto en Facturas',7,73,7,80);
insert into `appmenus` (`aplicacion`,`Name`,`caption`,`indice`,`padre`,`orden`,`Contador`) values ('Arigasol','mnE_Util','-',6,73,6,79);
insert into `appmenus` (`aplicacion`,`Name`,`caption`,`indice`,`padre`,`orden`,`Contador`) values ('Arigasol','mnE_Util','Declaración Gasóleo Profesional',5,73,5,78);
insert into `appmenus` (`aplicacion`,`Name`,`caption`,`indice`,`padre`,`orden`,`Contador`) values ('Arigasol','mnE_Util','-',4,73,4,77);
insert into `appmenus` (`aplicacion`,`Name`,`caption`,`indice`,`padre`,`orden`,`Contador`) values ('Arigasol','mnE_Util','Cambios Registros',3,73,3,76);

